name: Build & Publish ICS (3x daily)

on:
  schedule:
    - cron: '0 12 * * *'  # 09:00 BRT
    - cron: '0 16 * * *'  # 13:00 BRT
    - cron: '0 20 * * *'  # 17:00 BRT
  workflow_dispatch: {}    # permite rodar manualmente

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: agent_crf_ics_v0_2
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # instala dependências (inclui pyyaml)
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml python-dateutil pytz requests beautifulsoup4 lxml pdfplumber

      - name: Build calendars & CSVs
        run: python agent.py

      - name: Upload artifact (out/)
        uses: actions/upload-pages-artifact@v3
        with:
          path: agent_crf_ics_v0_2/out

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
